### ISSUE TITLE
台北市大安區泰順街50巷(R5296988)

### ISSUE THREAD

**Issue by theoneisneo** [dboyliao/RentHouse#19]
https://rent.591.com.tw/rent-detail-5296988.html

這個好像可以考慮? 28p稍微小一點點但或許還行.

**Comment by dboyliao** [comment]
可啊~
我看看這兩天跟他約個時間看~
我會約星期四或五這樣~
除非屋主要別的時間~

**Comment by dboyliao** [comment]
頁面關閉。
